const theme: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': {
    color: '#3E2B1E',
    background: '#F5F0EB',
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: 1.6,
    tabSize: 4,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#3E2B1E',
    background: '#F5F0EB',
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: 1.6,
    tabSize: 4,
    hyphens: 'none',
    padding: '1rem',
    margin: 0,
    overflow: 'auto',
    borderRadius: '0.75rem',
  },
  comment: { color: '#8B7D72', fontStyle: 'italic' },
  prolog: { color: '#8B7D72' },
  doctype: { color: '#8B7D72' },
  cdata: { color: '#8B7D72' },
  punctuation: { color: '#A0897A' },
  namespace: { opacity: 0.7 },
  property: { color: '#9C6B4E' },
  tag: { color: '#9C6B4E' },
  boolean: { color: '#B8754A' },
  number: { color: '#B8754A' },
  constant: { color: '#B8754A' },
  symbol: { color: '#B8754A' },
  deleted: { color: '#B53A2A' },
  selector: { color: '#5D7A4A' },
  'attr-name': { color: '#5D7A4A' },
  string: { color: '#5D7A4A' },
  char: { color: '#5D7A4A' },
  builtin: { color: '#5D7A4A' },
  inserted: { color: '#5D7A4A' },
  operator: { color: '#7A6A5A' },
  entity: { color: '#7A6A5A', cursor: 'help' },
  url: { color: '#7A6A5A' },
  '.language-css .token.string': { color: '#7A6A5A' },
  '.style .token.string': { color: '#7A6A5A' },
  variable: { color: '#7A6A5A' },
  atrule: { color: '#9C6B4E' },
  'attr-value': { color: '#5D7A4A' },
  keyword: { color: '#9C6B4E' },
  function: { color: '#5D4432' },
  'class-name': { color: '#8B6914' },
  regex: { color: '#B8754A' },
  important: { color: '#B8754A', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
}

export const cafeCodeTheme: any = theme
